// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $molecules_stepper from "./routes/molecules/stepper.tsx";
import * as $demo_component_docs_page from "./islands/demo/component-docs-page.tsx";
import * as $molecules_stepper_1 from "./islands/molecules/stepper.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
    "./routes/molecules/stepper.tsx": $molecules_stepper,
  },
  islands: {
    "./islands/demo/component-docs-page.tsx": $demo_component_docs_page,
    "./islands/molecules/stepper.tsx": $molecules_stepper_1,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
